[licenses]
confidence-threshold = 0.90
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "BSD-3-Clause",
    "Zlib",
    "ISC",
]
private = { ignore = true }

[bans]
multiple-versions = "allow"

[bans.build]
executables = "deny"

[advisories]
# TODO: When dropping support of old OTel crate versions, this can be cleaned up.
ignore = [
    "RUSTSEC-2025-0055", # For backward-compatibility
    "RUSTSEC-2024-0387", # For backward-compatibility
]
