[package]
name = "actix-identity"
version = "0.4.0-beta.7"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Identity service for Actix Web"
keywords = ["actix", "auth", "identity", "web", "security"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras.git"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_identity"
path = "src/lib.rs"

[dependencies]
actix-service = "2"
actix-utils = "3"
actix-web = { version = "4.0.0-beta.18", default-features = false, features = ["cookies", "secure-cookies"] }

futures-util = { version = "0.3.7", default-features = false }
serde = "1.0"
serde_json = "1.0"
time = "0.3"

[dev-dependencies]
actix-http = "3.0.0-beta.15"
actix-rt = "2"
