[package]
name = "actix-identity"
version = "0.3.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Identity service for Actix web"
readme = "README.md"
keywords = ["actix", "auth", "identity", "web", "security"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras.git"
documentation = "https://docs.rs/actix-identity/"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_identity"
path = "src/lib.rs"

[dependencies]
actix-service = "2.0.0-beta.4"
actix-web = { version = "4.0.0-beta.1", default-features = false, features = ["secure-cookies"] }

futures-core = { version = "0.3.7", default-features = false }
futures-util = { version = "0.3.7", default-features = false }
pin-project-lite = "0.2"
serde = "1.0"
serde_json = "1.0"
time = { version = "0.2.7", default-features = false, features = ["std"] }

[dev-dependencies]
actix-rt = "2"
actix-http = "3.0.0-beta.1"
bytes = "1"
