[package]
name = "prost-example"
version = "0.3.0"
authors = ["kingxsp <jin.hb.zh@outlook.com>"]

[dependencies]
bytes = "0.4"
env_logger = "*"

prost = "0.4"
prost-derive = "0.4"

actix = "0.8.1"
actix-web = "1.0.0-rc"
actix-protobuf = { path="../../" }