name: CI (Linux, MSRV)

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.39.0

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:5.0.7
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      redis-cluster:
        image: grokzen/redis-cluster:5.0.7
        ports:
          - 7000:7000
          - 7001:7001
          - 7002:7002
          - 7003:7003
          - 7004:7004
          - 7005:7005

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Launch docker-compose
        run: |
          docker-compose up -d
          host="$(
            docker ps -q -f name=redis0 |
            xargs docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
          )"
          while !  printf "cluster info\\n quit\n" | curl -v telnet://${host}:16379 | grep cluster_state:ok; do
            sleep 0.3
          done

      - name: Override /etc/resolv.conf
        run: |
          consul_ip="$(
            docker ps -q -f name=consul |
            xargs docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
          )"
          sudo mv /etc/resolv.conf /etc/resolv.conf.bak
          echo "nameserver ${consul_ip}" | sudo tee /etc/resolv.conf
          while test -z "$(dig +short redis.service.dc1.consul)"; do
            sleep 0.3
          done

      - name: tests (1.39.0)
        if: matrix.version == '1.39.0'
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --package=actix-cors
                --package=actix-protobuf
                --package=actix-redis
                --package=actix-web-httpauth
                --all-features --no-fail-fast -- --nocapture

      - name: Revert /etc/resolv.conf
        run: sudo mv -f /etc/resolv.conf.bak /etc/resolv.conf
        if: always()
